name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Usando la versión correcta de Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usando el secreto correctamente
        password: ${{ secrets.DOCKER_PASSWORD }}  # Usando el secreto correctamente

    - name: Build Docker image
      run: |
        docker build -t practica-devops .

    - name: Push Docker image
      run: |
        docker push practica-devops
1